-- WHERE NOT EXISTS를 쓰면 차집합을 구할 수 있다!
-- SQL 2005 이상은 WHRE문 자리에 EXCEPT 사용 가능

SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE NOT EXISTS
(SELECT *
 FROM ANIMAL_INS I
 WHERE I.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID)
 ORDER BY ANIMAL_ID;